language: ruby
rvm:
  - 2.7.3
  - 3.0
  - ruby-head
branches:
  except:
    - "readme-edits"
before_install:
  - gem update --system

matrix:
  allow_failures:
    - rvm: ruby-head
    
script: 
  - bundle exec rake spec

env:
  global:
    - AVOID_TRAVIS=true  