language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
branches:
  except:
    - "readme-edits"
before_install:
  - gem update --system

matrix:
  allow_failures:
    - rvm: ruby-head
    
script: 
  - bundle exec rake spec