require_relative 'utils/build_help'
require_relative 'utils/create_routine_thread'
require_relative 'utils/get_bots_created'
require_relative 'utils/get_channels_name_and_id'
require_relative 'utils/get_help'
require_relative 'utils/get_routines'
require_relative 'utils/get_rules_imported'
require_relative 'utils/remove_hash_keys'
require_relative 'utils/update_bots_file'
require_relative 'utils/update_routines'
require_relative 'utils/update_rules_imported'
require_relative 'utils/update_shortcuts_file'
require_relative 'utils/save_stats'
require_relative 'utils/get_repls'
require_relative 'utils/update_repls'
require_relative 'utils/answer'
require_relative 'utils/answer_delete'

